# Generated by Django 5.2 on 2025-04-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video_analysis/')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='video_reports/')),
                ('dominant_emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('emotion_percentages', models.JSONField(blank=True, default=dict)),
                ('emotion_durations', models.JSONField(blank=True, default=dict)),
                ('total_frames', models.IntegerField(default=0)),
                ('video_duration', models.FloatField(default=0)),
                ('emotion_transitions', models.IntegerField(default=0)),
                ('transition_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Video Analyses',
            },
        ),
    ]
