# Generated by Django 5.2 on 2025-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emotion_Video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='video_audio/'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='sentiment_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
