# Generated by Django 5.2 on 2025-04-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speech2Text', '0002_alter_speechanalysis_prediction_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speechanalysis',
            name='prediction_value',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speechanalysis',
            name='sentiment',
            field=models.CharField(default=0.5, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speechanalysis',
            name='transcription',
            field=models.TextField(default=0.5),
            preserve_default=False,
        ),
    ]
