# Generated by Django 5.2 on 2025-04-12 00:19

import RealTimeVideo.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=RealTimeVideo.models.get_file_path)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('emotion_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('emotion_confidence', models.FloatField(default=0)),
                ('landmark_data', models.JSONField(blank=True, default=dict)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='frame_captures')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='RealTimeVideo.videostream')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('stream', 'timestamp')},
            },
        ),
    ]
