# Generated by Django 5.2 on 2025-04-19 15:30

import RealTimeVideo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeVideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=RealTimeVideo.models.get_file_path)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('emotion_percentages', models.JSONField(blank=True, default=dict)),
                ('total_frames', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Real-time Analyses',
            },
        ),
        migrations.AlterModelOptions(
            name='frameanalysis',
            options={},
        ),
        migrations.RenameField(
            model_name='frameanalysis',
            old_name='emotion_confidence',
            new_name='confidence',
        ),
        migrations.AlterUniqueTogether(
            name='frameanalysis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='frameanalysis',
            name='frame_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frameanalysis',
            name='emotion',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='frameanalysis',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='frameanalysis',
            name='session',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='RealTimeVideo.realtimeanalysis'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='frameanalysis',
            name='landmark_data',
        ),
        migrations.RemoveField(
            model_name='frameanalysis',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='frameanalysis',
            name='stream',
        ),
        migrations.DeleteModel(
            name='VideoStream',
        ),
    ]
